index:
    path:     /
    methods: 'GET'
    defaults: { _controller: AppBundle:Default:index }
add:
    path:     /add
    defaults: { _controller: AppBundle:Default:add }
update:
    path:     /update
    methods: 'POST'
    defaults: { _controller: AppBundle:Default:update }
remove:
    path:     /remove
    methods: 'POST'
    defaults: { _controller: AppBundle:Default:remove }
get:
    path:     /get
    methods: 'GET'
    defaults: { _controller: AppBundle:Default:get }
list:
    path:     /list/{page}
    methods: 'GET'
    defaults: { _controller: AppBundle:Default:list, page: null }
