AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        traces:
            targetEntity: AppBundle\Entity\Trace
            mappedBy: user
    lifecycleCallbacks: {  }
